apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ktp5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ktp5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ktp5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ktp5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ktp5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pmzr-tenant/rhtap-demo-app/hacbs-test-project-ktp5@sha256:d2d7950d3bf36d9c12ac8c146c9d9b25f2012a2a36243fd5d9e86dfaeebcde19
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
